### ISSUE TITLE
Dockerhub Images Available After New Version

### ISSUE THREAD

**Issue by YazzyYaz** [multi-geth/multi-geth#104]
This isn't a bug, but a feature request for devops.

It'd be very cool if after every new version that's released, an image is built on Docker and pushed to Dockerhub, kinda like what Parity does.

This helps a lot of us running multiple nodes in clusters, as we can easily pull the multigeth version tagged with `:latest` from Dockerhub and run that with new changes.

**Comment by sorpaas** [comment]
I have just created an automate build: https://hub.docker.com/r/multigeth/multi-geth

**Comment by YazzyYaz** [comment]
Awesome, thanks @sorpaas!

**Comment by BelfordZ** [comment]
Does it always just rebuild and tag with latest? 
Will it share tag names with the github releases?

**Comment by sorpaas** [comment]
It will build any new tags that looks like vx.x.x and yeah, every master push triggers a rebuild.

**Comment by sorpaas** [comment]
Docker image builds fine now. Closing this issue.
