### ISSUE TITLE
JSON RPC eth_submitHashrate not implemented in latest release of multi-geth v1.9.3 (and v1.9.2)

### ISSUE THREAD

**Issue by wykan** [multi-geth/multi-geth#115]
#### System information

Geth version: MultiGeth/v1.9.3-stable-0b84e2b0/windows-amd64/go1.12.7
OS & Version: Windows

#### Expected behaviour
No errors or warning. 
Multi-Geth to implement the eth_submitHashrate for RPC as it's part of Go-Ethereum (Geth) or OpenRPC JSON RPC calls.
https://github.com/ethereumproject/go-ethereum/wiki/JSON-RPC#eth_submithashrate
https://github.com/etclabscore/ethereum-json-rpc-specification
or [OpenRPC](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/etclabscore/ethereum-json-rpc-specification/master/openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false)

#### Actual behaviour
Geth's Log:
WARN [09-11|09:03:53.988] Served eth_submitHashrate                conn=127.0.0.1:49702 reqid=1 t=0s       err="the method eth_submitHashrate does not exist/is not available"

Miner's Console Log:
Eth: Failed to submit hashrate: Exception -32601 : METHOD_NOT_FOUND: The method being requested is not available on this server: the method eth_submitHashrate does not exist/is not available

Unable to find any block (so far)
No solutions submitted to Geth server (so far) by Miners (Pheonix Miner). 

Hope Multi Geth v1.9.3 (and later versions) could implement eth_submitHashrate JSON RPC.
as per https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_submithashrate
and
https://github.com/ethereumproject/go-ethereum/wiki/JSON-RPC#eth_submithashrate

#### Steps to reproduce the behaviour
Run multi-geth and miner (Pheonix Miner) connected to multi-geth on local machine http://127.0.0.1.   Miner able to communicate with Multi-Geth and able to receive new jobs.   But so far did not (or could not) submit any solutions.

#### Backtrace

````
[backtrace]
````

**Comment by BelfordZ** [comment]
I think the general consensus is to deprecate this method.

**Comment by wykan** [comment]
> I think the general consensus is to deprecate this method.

If deprecated, it would have been marked as (deprecated) in the Go-Ethereum and Ethereum latest supported JSON RPC documentation; but it was not.  latest version of Miners still use the RPC call to submit Hashrate to the Geth server.

**Comment by BelfordZ** [comment]
I'd recommend looking to [this](https://github.com/etclabscore/ethereum-json-rpc-specification) and/or [this](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/etclabscore/ethereum-json-rpc-specification/master/openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false) instead of the go-ethereum docs. It contains an OpenRPC document which forms the specification for all ethereum clients to use. Its already in use with multi-geth. You can call the `rpc.discover' method and it will return you the supported methods.

**Comment by wykan** [comment]
> I'd recommend looking to [this](https://github.com/etclabscore/ethereum-json-rpc-specification) and/or [this](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/etclabscore/ethereum-json-rpc-specification/master/openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false) instead of the go-ethereum docs. It contains an OpenRPC document which forms the specification for all ethereum clients to use. Its already in use with multi-geth. You can call the `rpc.discover' method and it will return you the supported methods.

I am just a user. The main thing is for multi-geth which is based on Go-Ethereum to agree with the developer of miners.  As the Pheonix Miners or cgminers or others would based on documentation from Go-Ethereum for their implementation. I am not sure if this RPC call is the cause of the miner not able to find a solution which is serious to the user. If so, would hope that multi geth could implement this RPC call for eth_submitHashrate.

**Comment by wykan** [comment]
> I'd recommend looking to [this](https://github.com/etclabscore/ethereum-json-rpc-specification) and/or [this](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/etclabscore/ethereum-json-rpc-specification/master/openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false) instead of the go-ethereum docs. It contains an OpenRPC document which forms the specification for all ethereum clients to use. Its already in use with multi-geth. You can call the `rpc.discover' method and it will return you the supported methods.

Based on the links that you have provided for OpenRPC document, 
https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/etclabscore/ethereum-json-rpc-specification/master/openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false

OpenRPC did include eth_submitHashrate as a supported JSON RPC call.  Please see the documentation that you have provided the link to. There is no mention of it being deprecated.

**Comment by BelfordZ** [comment]
I understand your predicament, but I urge you to open an issue with the miner vendor.

If we add methods for no reason other than to make other peoples code work, we end up with many useless methods. 

As for the deprecation in the ethereum-json-rpc-spec, I've opened a PR to do just that a few hours ago after seeing this issue come up.

**Comment by BelfordZ** [comment]
That said, maybe @sorpaas @whilei  & friends have a different outlook than I on this.

**Comment by sorpaas** [comment]
As far as I know we still have the code https://github.com/multi-geth/multi-geth/blob/569a2b039b560836de397c2e059497719aea49a6/consensus/ethash/api.go#L96 and there’s no past commit that removed it. Let me check what might have been wrong.

**Comment by wykan** [comment]
> As far as I know we still have the code
> 
> https://github.com/multi-geth/multi-geth/blob/569a2b039b560836de397c2e059497719aea49a6/consensus/ethash/api.go#L96
> 
> and there’s no past commit that removed it. Let me check what might have been wrong.

Thanks.  Awesome WeiTang.

**Comment by wykan** [comment]
> As far as I know we still have the code
> 
> https://github.com/multi-geth/multi-geth/blob/569a2b039b560836de397c2e059497719aea49a6/consensus/ethash/api.go#L96
> 
> and there’s no past commit that removed it. Let me check what might have been wrong.

[https://github.com/multi-geth/multi-geth/blob/569a2b039b560836de397c2e059497719aea49a6/consensus/ethash/api.go#L109](url)

In the codes, what does it mean by "(line 109)	// Block until hash rate submitted successfully." in the comment for eth_submitHashrate function?
Does it mean that if my miner has problems submitting the hashrate, my miner will be blocked by Multi-Geth until hashrate is submitted successfully?  Could this be the reason why my miner could not successfully find a solution or a block because according to Zachary, this function has been deprecated or disabled in multi-geth, that prevents miners in finding blocks/solutions ?

My miner is a full rig of many GPUs and mining for days but could not find a block or generate a solution for ETC (not ETH).  Could this be the reason why my miner could not find a solution to find a block when my miner was unable to submit the Hashrate?

**Comment by sorpaas** [comment]
@wykan `submitHashRate`, as far as I understand, is only used for tracing external miners. The line you showed just means that the RPC request will block until the rate is passed on through the channel. It shouldn't block any other things.

If you still think miners might not be working, maybe consider comparing your hashrate with the network hashrate, and calculate how many blocks you should be mining on average per day or per week. If you have trouble calculating that, let me know.

**Comment by sorpaas** [comment]
@wykan Looks like the issue is that the method name is case sensitive. In the mining software it should be `eth_submitHashRate` instead of `eth_submitHashrate`. This is, however, not really consistent because when you do fetch hashrate, you write it as `eth_GetHashrate`.

I'll check whether it's the same behavior in upstream. If so, this maybe classified as expected behavior as changing it may break other stuff. But we may consider just making RPC methods case insensitive.

Besides all this, please also make sure you have enabled the required RPC methods to make it work: `--rpcapi=eth`.

**Comment by sorpaas** [comment]
Upstream has the same behavior. So I'm going to mark this as resolved. Let me know if you still suffer from this issue.

**Comment by meowsbits** [comment]
I can't reproduce:

```
~# curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_submitHashrate","params": ["0x444444444444444", "0xa477fc314a104a79696fda96ccc63a07c5e5902c839deff61ee294d6afa8eb65"],"id":1}' localhost:8540
{"jsonrpc":"2.0","result":true,"id":1}
```

**Comment by wykan** [comment]
> I can't reproduce:
> 
> ```
> ~# curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_submitHashrate","params": ["0x444444444444444", "0xa477fc314a104a79696fda96ccc63a07c5e5902c839deff61ee294d6afa8eb65"],"id":1}' localhost:8540
> {"jsonrpc":"2.0","result":true,"id":1}
> ```

Able to send me the geth for yours that you could not reproduce the problem? Maybe it has the codes in yours.

**Comment by wykan** [comment]
> @wykan Looks like the issue is that the method name is case sensitive. In the mining software it should be `eth_submitHashRate` instead of `eth_submitHashrate`. This is, however, not really consistent because when you do fetch hashrate, you write it as `eth_GetHashrate`.
> 
> I'll check whether it's the same behavior in upstream. If so, this maybe classified as expected behavior as changing it may break other stuff. But we may consider just making RPC methods case insensitive.
> 
> Besides all this, please also make sure you have enabled the required RPC methods to make it work: `--rpcapi=eth`.

I did not specifically enable eth for RPC API. just activated the RPC in general.  Should that activate all RPC API in all libraries supported including eth?  The method eth_submitHashrate is reported by multi geth console log.  should it be eth_submitHashRate ?
From your documentation of openRPC, https://github.com/etclabscore/ethereum-json-rpc-specification/blob/master/openrpc.json
it states that it's eth_submitHashrate instead of eth_submitHashRate which the miner is correct

But meowsbit is using eth_submitHashrate to test without error. Maybe I can get the geth from meowsbit to test again. Maybe meowsbits multi geth  version of geth has no problem compared to the one I downloaded from the repository.

**Comment by BelfordZ** [comment]
@wykan My bad for the confusion, I didn't mean to say that it wasn't implemented by multi-geth, but rather that it probably shouldn't be.

The link you provided to the ethereum-json-rpc-specification is the definitive documentation of the base requirements of any ethereum json rpc api. That said, eth_submitHashrate is indeed the correct case.
