### ISSUE TITLE
Support "ECIP-1061" Ethereum Classic contentious hard fork

### ISSUE THREAD

**Issue by sorpaas** [multi-geth/multi-geth#126]
The recent Aztlán Upgrade core dev meeting has concluded. In the meeting, we have decided to proceed with option ECIP-1072:

> Wei: Just to be clear? Are we using ECIP 1072? How long should "last call" last?
> Afri: Three weeks "last call" would be sufficient to evaluate Istanbul on EF network
> Everyone: Sounds good

However, one of the ECIP editors, Afri, decided to ignore the community consensus, and move forward with ECIP-1061 with clear objections (https://github.com/ethereumclassic/ECIPs/pull/199#pullrequestreview-323755348) echoed by others (https://github.com/ethereumclassic/ECIPs/pull/199#issuecomment-559185183). This technically constitutes a contentious hard fork on Ethereum Classic.

As a result, to support this new chain (initiated by ECIP-1061), we'll need to add a new chain config. I'm tentatively calling it "ecip1061". This new chain can be ran by users using `--ecip1061` flag, such as:

```
mv ~/.ethereum/classic ~/.ethereum/ecip1061
./geth --ecip1061
```

multi-geth will continue to follow the community consensus specified by ECIP-1072.

**Comment by GregTheGreek** [comment]
I would suggest doing the following:

1) Renaming this to something more appropriate.

If you're going to single a person out like this you should own up to it yourself.

This is in appropriate behavior, borderline childish. I will not support this until there is a naming change.

@bobsummerwill @yazzyyaz @tzdybal (on mobile, I would tag more) I hope you all agree.

**Comment by sorpaas** [comment]
@GregTheGreek This is rather to demonstrate to @bobsummerwill of how "borderline childish" Afri's behavior was recently.

The clear consensus in the meeting to move forward with ECIP-1072 ignored by Afri. Multiple attempts were made to frame it wrongly. Clear objections (https://github.com/ethereumclassic/ECIPs/pull/199#pullrequestreview-323755348) were dismissed (https://github.com/ethereumclassic/ECIPs/pull/199#event-2837816513) during the ECIP editing process, which is a clear violation of the editing protocol.

I'll be changing the chain name to "ecip1061" to avoid "name calling" or "singling a person out". Hope that satisfies you.

**Comment by BelfordZ** [comment]
> - clear objections were dismissed

I can attest to this happening in previous hard fork discussion as well.

**Comment by sorpaas** [comment]
We have decided not to support ECIP-1061 at all, given there's no community support of it.

**Comment by soc1c** [comment]
> "we"
> 
> "no community support"

:roll_eyes:

**Comment by shanejonas** [comment]
I support only 1061 as that is the original ecip and should be updated appropriately and follow the ECIP process. 

creating a second competing ecip 1072 was not following process, it should have been a PR to 1061.

having multiple is creating political motivations for their number to be accepted over another.
