### ISSUE TITLE
ETC Pool switch to multi-geth but work not ready(finished sync)

### ISSUE THREAD

**Issue by ahonder** [multi-geth/multi-geth#132]
Hi there,

i have mining pool and it was worked good with classic geth. switched to multi-geth 1.9.7. after fully synced(controlled from console too,fully synced and only importing blocks) tried with mining client and showing error "work not ready" and same error from console too. Pool software is sammy007 fork;
https://github.com/techievee/ethash-mining-pool

what is the problem?

fully synced with "geth --classic", also created a wallet with "geth --classic account new" and unlocked too.

Regards
#### System information

Geth version: `1.9.7`
OS & Version: Ubuntu 16.04
Commit hash : (if `develop`)

**Comment by BelfordZ** [comment]
Please open an issue with the mining pool, or be more specific about what part of multi-geth is not working.
