### ISSUE TITLE
sha256 files on release 1.9.8 not properly formatted

### ISSUE THREAD

**Issue by jcvernaleo** [multi-geth/multi-geth#135]
The sha256 files from 1.9.8 for all platforms contain the full path from the build artifacts which prevent verifying the binaries:
```

jcv@triforce tmp $ sha256sum -c multi-geth-linux.zip.sha256 
sha256sum: /home/vsts/work/1/a/multi-geth-linux.zip: No such file or directory
/home/vsts/work/1/a/multi-geth-linux.zip: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
jcv@triforce tmp $ cat multi-geth-linux.zip.sha256 
84face44c4eeff859ca76a07a06855cd3acf43668df73e357b0ae3600cda5ee7  /home/vsts/work/1/a/multi-geth-linux.zip
```

Previous releases do not contain the path info allowing sha256sum to properly verify the file.

**Comment by fish-sammy** [comment]
Any update here? The issue exists in all versions from 1.9.8 to 1.9.12.

**Comment by jcvernaleo** [comment]
Closing this issue since I don't think multi-geth is active any longer.
