### ISSUE TITLE
not sync

### ISSUE THREAD

**Issue by slavserver** [multi-geth/multi-geth#136]
#### System information

Geth version: `v1.9.8`
OS & Version: ubuntu 18.04

 Dropping unsynced node during fast sync  id=6a11e651a381bccf conn=inbound addr=47.74.48.28:33896     type=Geth/v5.0.0-ac28808/linux/go1.9.4
WARN [02-28|17:55:42.394] Dropping unsynced node during fast sync  id=5d11d77f518afb52 conn=dyndial addr=51.15.122.80:30303    type=Geth/Apollo/v1.9.1-stable-b7b2f60f/linux-arm64/go1.12.7
WARN [02-28|17:55:47.360] Dropping unsynced node during fast sync  id=78fcc38dd40639fd conn=inbound addr=73.231.211.249:41860  type=Getc/v6.0.8/linux/go1.12.7
INFO [02-28|17:55:47.897] Looking for peers                        peercount=1  tried=139 static=0
WARN [02-28|17:55:50.113] Dropping unsynced node during fast sync  id=dd420203b26236de conn=inbound addr=35.176.94.110:61640   type=Geth/v1.8.6-stable-12683fec/linux-amd64/go1.10
INFO [02-28|17:55:58.037] Looking for peers                        peercount=1  tried=168 static=0
WARN [02-28|17:55:59.609] Dropping unsynced node during fast sync  id=b6517a25744ebcd2 conn=inbound addr=47.75.188.57:41486    type="Geth/v5.5.2-be43774/linux/go1.9.7/hzy etherum"
WARN [02-28|17:56:07.667] Dropping unsynced node during fast sync  id=67dd634c9820b5ae conn=inbound addr=54.235.31.238:58388   type=Parity-Ethereum/v2.6.2-beta-25936ae-20190829/x86_64-linux-gnu/rustc1.36.0

**Comment by sorpaas** [comment]
Have you tried to just wait a while? Currently there're not a lot of synced nodes in ETC, so due to network conditions, it may take some time before the node finds a peer it can sync with.

**Comment by slavserver** [comment]
Yes, I understand, but the wait is more than 48 hours, and no more than 1 million 900 thousand blocks are synchronized ... With the previous base (1,9,7), which is fully synchronized, it works very very poorly, I would even say - through the ass)))

 Now I will test 1,9,9

**Comment by slavserver** [comment]
all the same ... everything is bad ... why didn’t you compatible with nodes 1.9.7 and other versions? - that's why everything is so bad works!

tnx

**Comment by sorpaas** [comment]
@slavserver I noticed you're using fast sync. It's currently a known issue that there're some non-upgraded pre-Byzantium nodes on the network emitting faulty 8772000 block. It's causing issues but there's not much we can do about it. Try full sync mode instead -- you should be able to finish syncing under a day `--syncmode full`

**Comment by slavserver** [comment]
ok, testing

**Comment by sorpaas** [comment]
If initially full sync does not work, try purge the database first 
```
mv ~/.ethereum/classic ~/.ethereum/classic.bak
```

**Comment by slavserver** [comment]
the same problem, peers 0-1 ... on the old base (1.9.7), which is completely synchronized, peers are not found at all .. I think that the solution to this problem should be compatibility with nodes of previous versions ... 


tnx

**Comment by sorpaas** [comment]
> why didn’t you compatible with nodes 1.9.7 and other versions? - that's why everything is so bad works

All nodes should be compatible. There were known issues that geth and openethereum nodes sometimes refuse to connect to each other, but for most of the cases it's just because ETC and Ethereum share the same network ID, so peers connect to too many Ethereum nodes that pollute the pool.

**Comment by slavserver** [comment]
I think you need to install and make sure that everything is bad...
And not work --rpcapi="db"

**Comment by sorpaas** [comment]
I'll take a deeper look soon. However, I indeed recently finished a full sync using 1.9.8 without any problems.

**Comment by sorpaas** [comment]
> And not work --rpcapi="db"

Can you explain what doesn't work?

**Comment by slavserver** [comment]
ERROR[02-28|17:09:21.575] Unavailable modules in HTTP API list     unavailable=[db] available="[admin debug web3 eth txpool personal ethash miner net]"

**Comment by slavserver** [comment]
in general, we are waiting for a normal working release ... I'm sure you will succeed ... 1.9.8 1.9.9 - do not work properly, and using these releases for pools is dangerous

tnx

**Comment by sorpaas** [comment]
@slavserver The problem for syncing is identified and we're working on a fix. Sorry for the inconvenience.

**Comment by slavserver** [comment]
Thank you, I believed in you ... waiting for a new release )))

**Comment by sorpaas** [comment]
@slavserver v1.9.10 is released which should fix the syncing issue. Please give it a try! https://github.com/multi-geth/multi-geth/releases/tag/v1.9.10

Sorry again for the inconvenience and thank you for reporting the bug!

**Comment by slavserver** [comment]
big TNX !!! )

**Comment by slavserver** [comment]
but why doesn’t work --rpcapi = "db" ? this is normal? if so, then I will no longer pay attention to it.

ERROR[02-28|21:49:11.083] Unavailable modules in HTTP API list     unavailable=[db] available="[admin debug web3 eth txpool personal ethash miner net]"

**Comment by sorpaas** [comment]
@slavserver I checked and it looks like the `db` RPC APIs were removed around geth 1.4. Are you sure you still need those APIs? Those are quite obsolete APIs for local storage access. If you're not sure, remove `--rpcapi=db` and see if your program still works correctly.

**Comment by slavserver** [comment]
no, I don’t need ... I just drew attention to this ... I understand you ... Thanks again for your work
