### ISSUE TITLE
Node/Block Syncing issue

### ISSUE THREAD

**Issue by W3-MajorArif** [multi-geth/multi-geth#138]
Hi there,

I have 2 nodes deployed on two separate AWS machines for Ethereum Classic kotti test net. I was using multi-geth version  1.9.7-stable-fbf01360 before.
Today I've updated one machine multi-geth version to v1.9.11, which said fixes kotti and mordor issue.
But while it was running it faced some error and dropped peers and stopped syncing. Error code 

########## BAD BLOCK #########
Mar 11 07:20:06 ip-172-31-14-228 geth[9787]: Chain config: {ChainID: 6 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 716617 Byzantium: 716617 Constantinople: 1705549 Petersburg: 1
Mar 11 07:20:06 ip-172-31-14-228 geth[9787]: Number: 2203328
Mar 11 07:20:06 ip-172-31-14-228 geth[9787]: Hash: 0x6caac1ffc8186c3a57039d464b367af3d51dce0684752c2c317a23e8349c8cc3
Mar 11 07:20:06 ip-172-31-14-228 geth[9787]:          0: cumulative: 32312 gas: 32312 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x5cddbcc23b714ffe86db5487cdae115d0c0bc10a35d199df
Mar 11 07:20:06 ip-172-31-14-228 geth[9787]: Error: invalid gas used (remote: 28412 local: 32312)
Mar 11 07:20:06 ip-172-31-14-228 geth[9787]: ##############################
Mar 11 07:20:06 ip-172-31-14-228 geth[9787]:
Mar 11 07:20:06 ip-172-31-14-228 geth[9787]: WARN [03-11|07:20:06.854] Synchronisation failed, dropping peer    peer=e88a70f4df859857 err="retrieved hash chain is invalid"
Mar 11 07:20:16 ip-172-31-14-228 geth[9787]: INFO [03-11|07:20:16.085] Looking for peers                        peercount=1 tried=42  static=0

I'm not sure whether this is library issue or not. So I posted it here. Please help me on this.
NOTE: My another machine which runs multi-geth 1.9.7 is working fine still now.

THanks

**Comment by meowsbits** [comment]
AFAIK the Kotti network isn't yet "rescued" from the Aztlan->Phoenix Fork configuration revision

http://kotti.etcstats.org/
https://github.com/ethereumclassic/ECIPs/issues/262

**Comment by q9f** [comment]
It should work now.

**Comment by W3-MajorArif** [comment]
Yes it is. THanks a lot @q9f . Sorry for late response.
