### ISSUE TITLE
feature: support open rpc service discovery

### ISSUE THREAD

**Issue by meowsbits** [multi-geth/multi-geth#39]
The open rpc idea is a huge and really impactful one, so I'm not going to laundry list it's perks here. Instead, focus on exploring and spec'ing implementation patterns and progress.

**Comment by shanejonas** [comment]
#### Proposal: Add OpenRPC `rpc.discover` to multi-geth

here is the formal proposal to add this feature to `multi-geth`:

https://github.com/etclabscore/ECIPs/blob/master/ECIPs/ECIP-1053.md
