### ISSUE TITLE
feature[documentation]: wiki page for hard fork/feature references

### ISSUE THREAD

**Issue by meowsbits** [multi-geth/multi-geth#57]
Would be useful as a reference for documenting how we've translated hardforks to their associated features

**Comment by whilei** [comment]
Have initialized with https://github.com/ethoxy/multi-geth/wiki/Ethereum-Hardfork-Reference-Sheet.

There are probably better ways of displaying the information (a table?)

Could include similar references for other relevant networks, eg. Classic as well. If TODO, make an issue for this/these.
