### ISSUE TITLE
refactor chain configuration parameters and logic to independent files

### ISSUE THREAD

**Issue by meowsbits** [multi-geth/multi-geth#89]
Collecting varying iterations of chain parameters adjacent one another (line over line) causes merge complexity. 

This issue proposing, where possible, to refactor chain-specific parameters and logic to own-file patterns, thereby easing this workflow.

This would look something like:

Before:
```go
// params/chain_ids.go
const ChainAID = 1
const ChainBID = 2
```

After:
```go
// params/chain_ids_a.go
const ChainAID = 1
```

```go
// params/chain_ids_b.go
const ChainBID = 2
```

**Comment by meowsbits** [comment]
So as @tzdybal brought up, there are at least two possible approaches here.

1. One (additional) file per supported chain config.
2. One (additional) file for all non-ETH chain configs.

I'd lean toward 1. with my only reason being that eventually it might be interesting or beneficial to be able to use build tags selectively, and the cost of doing so (relative to many configs/one file) is a few extra files which seems cheap to me. And on principle: more granular and descriptive for set-and-forget configurations; exposes configurations to filesystem context in addition to text context.

**Comment by tzdybal** [comment]
Build tags is a great point. I'll implement the first approach.
