### ISSUE TITLE
Sync problem around block 1919629

### ISSUE THREAD

**Issue by tzdybal** [multi-geth/multi-geth#99]
As mentioned by @TokenHash, there is a sync disturbance close to block 1920000:
![Screen_Shot_2019-06-09_at_9 20 47_PM](https://user-images.githubusercontent.com/1138893/59254657-e6340b00-8c30-11e9-8476-a1d0040a8cfd.png)
![Screen_Shot_2019-06-09_at_9 33 16_PM](https://user-images.githubusercontent.com/1138893/59254658-e6cca180-8c30-11e9-91a3-d42bb9a186cc.png)

**Comment by meowsbits** [comment]
if this is for —classic, i expect this to have been addressed with #95

**Comment by tzdybal** [comment]
Problem is before DAO Fork - blocks should be same for both chains, so I would say that #95 may not be relevant.

**Comment by tzdybal** [comment]
I'm trying to reproduce right now. In case of error I'll switch to geth version with CHT fix.

**Comment by tzdybal** [comment]
@meowsbits was right. It's been fixed by #95.
I was able to reproduce problem using previous commit, and then fix the problem by running the latest version from master. We need to prepare release with a fix.
